name: .NET Core - Build Pipeline

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: MongoDBClient
        path: ./MongoDB/bin/Release/
    - name: Publish Nuget
      uses: rohith/publish-nuget@v2.0.0
      with:
        PROJECT_FILE_PATH: ./MongoDB/MongoDB.csproj
        NUGET_KEY: oy2m6rtzddkqjxxw5h5a2m6w5os3mdouzbuwtipcthofxe
      
